### ISSUE TITLE
Error running ember electron:make/package in new app

### ISSUE THREAD

**Issue by k-dauda** [adopted-ember-addons/ember-electron#515]
**Steps to reproduce**
```
1. ember new electron
2. cd electron
3. ember install ember-electron
4. ember electron:make or ember electron:package
```

**Versions**
```
kdauda-mac:electron kdauda$ npx ember -v
ember-cli: 3.19.0
node: 12.18.1
os: darwin x64
electron-forge: ^5.2.4
electron-prebuilt-compile: 8.2.0
ember-electron: ^2.10.2
electron-compile: ^6.4.4
electron-protocol-serve: ^1.4.0
electron-squirrel-startup: ^1.0.0
```

**The error output for make and package**
```
kdauda-mac:electron kdauda$ npx ember electron:make
cleaning up...
Built and assembled Electron project successfully. Stored in "/Users/kdauda/Desktop/electron/tmp/package_task-tmp_path-Ik3sqg21.tmp".
Packaging Electron project.
✖ Compiling Application

An unhandled error has occurred inside Forge:
Invalid or unexpected token
/Users/kdauda/Desktop/electron/tmp/package_task-tmp_path-Ik3sqg21.tmp/node_modules/electron-compile/lib/cli.js:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1041:15)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/kdauda/Desktop/electron/node_modules/electron-forge/dist/util/compile-hook.js:86:26
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/kdauda/Desktop/electron/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/kdauda/Desktop/electron/node_modules/bluebird/js/release/generators.js:97:49)
    at /Users/kdauda/Desktop/electron/node_modules/bluebird/js/release/generators.js:201:15
    at /Users/kdauda/Desktop/electron/node_modules/electron-forge/dist/util/ora-handler.js:46:5
✔ Preparing native dependencies
Making Electron project.
```

**Comment by rwwagner90** [comment]
@k-dauda I recommend using the latest beta https://ember-electron.js.org/versions/v3.0.0-beta.3/docs/
